### ISSUE TITLE
Fazer o MER e DER

### ISSUE THREAD

**Issue by Chigutti** [BaseTech-Inc/Tupa-Server#1]
Bora trabalhar, petralha!

- [x] MER
- [x] DER

**Comment by Mr-N-Dev** [comment]
![DER](https://user-images.githubusercontent.com/80842687/112765352-32596680-8fe3-11eb-9c18-bb4c502b321a.jpg)
[DER.pptx](https://github.com/BaseTech-Inc/Tupa-Server/files/6217925/DER.pptx)
[DER.pdf](https://github.com/BaseTech-Inc/Tupa-Server/files/6217926/DER.pdf)

**Comment by Mr-N-Dev** [comment]
> Bora trabalhar, petralha!
> 
> * [x]  MER
> * [x]  DER

[DER.pptx](https://github.com/BaseTech-Inc/Tupa-Server/files/6217948/DER.pptx)
[DER.pdf](https://github.com/BaseTech-Inc/Tupa-Server/files/6217949/DER.pdf)
![DER](https://user-images.githubusercontent.com/80842687/112765733-df80ae80-8fe4-11eb-86c6-20deb9d2119f.jpg)

**Comment by Mr-N-Dev** [comment]
[DER.pptx](https://github.com/BaseTech-Inc/Tupa-Server/files/6217973/DER.pptx)
[DER.pdf](https://github.com/BaseTech-Inc/Tupa-Server/files/6217975/DER.pdf)
![DER](https://user-images.githubusercontent.com/80842687/112766352-c88f8b80-8fe7-11eb-92cf-c29b954e2e31.jpg)
